// Date: 16/08/2014 7:45:46 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package spaceage.planets.aliens.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBinaryFemale extends ModelBase {
	//fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer Base;
    ModelRenderer Right;
    ModelRenderer Left;
    ModelRenderer Top;
    ModelRenderer TopLeft;
    ModelRenderer TopRight;
    ModelRenderer BottomLeft;
    ModelRenderer BottomRight;
    
    /**
     * Records whether the model should be rendered holding an item in the left hand, and if that item is a block.
     */
    public int heldItemLeft;

    /**
     * Records whether the model should be rendered holding an item in the right hand, and if that item is a block.
     */
    public int heldItemRight;
    public boolean isSneak;

    /** Records whether the model should be rendered aiming a bow. */
    public boolean aimedBow;
  
    public ModelBinaryFemale() {
    	textureWidth = 64;
    	textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      
      Base = new ModelRenderer(this, 0, 32);
      Base.addBox(-3F, 1F, -3F, 6, 4, 1);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      
      Right = new ModelRenderer(this, 0, 37);
      Right.addBox(3F, 2F, -3F, 1, 3, 1);
      Right.setRotationPoint(0F, 0F, 0F);
      Right.setTextureSize(64, 64);
      Right.mirror = true;
      setRotation(Right, 0F, 0F, 0F);
      
      Left = new ModelRenderer(this, 4, 37);
      Left.addBox(-4F, 2F, -3F, 1, 3, 1);
      Left.setRotationPoint(0F, 0F, 0F);
      Left.setTextureSize(64, 64);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      
      Top = new ModelRenderer(this, 0, 41);
      Top.addBox(-3F, 2F, -4F, 6, 2, 1);
      Top.setRotationPoint(0F, 0F, 0F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      
      TopLeft = new ModelRenderer(this, 0, 44);
      TopLeft.addBox(3F, 3F, -4F, 1, 1, 1);
      TopLeft.setRotationPoint(0F, 0F, 0F);
      TopLeft.setTextureSize(64, 64);
      TopLeft.mirror = true;
      setRotation(TopLeft, 0F, 0F, 0F);
      
      TopRight = new ModelRenderer(this, 4, 44);
      TopRight.addBox(-4F, 3F, -4F, 1, 1, 1);
      TopRight.setRotationPoint(0F, 0F, 0F);
      TopRight.setTextureSize(64, 64);
      TopRight.mirror = true;
      setRotation(TopRight, 0F, 0F, 0F);
      
      BottomLeft = new ModelRenderer(this, 0, 46);
      BottomLeft.addBox(1F, 4F, -4F, 2, 1, 1);
      BottomLeft.setRotationPoint(0F, 0F, 0F);
      BottomLeft.setTextureSize(64, 64);
      BottomLeft.mirror = true;
      setRotation(BottomLeft, 0F, 0F, 0F);
      
      BottomRight = new ModelRenderer(this, 6, 46);
      BottomRight.addBox(-3F, 4F, -4F, 2, 1, 1);
      BottomRight.setRotationPoint(0F, 0F, 0F);
      BottomRight.setTextureSize(64, 64);
      BottomRight.mirror = true;
      setRotation(BottomRight, 0F, 0F, 0F);
      
      this.body.addChild(Base);
      this.body.addChild(Left);
      this.body.addChild(Right);
      
      this.Base.addChild(Top);
      this.Base.addChild(BottomLeft);
      this.Base.addChild(BottomRight);
      
      this.Left.addChild(TopLeft);
      
      this.Right.addChild(TopRight);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    Base.render(f5);
    Right.render(f5);
    Left.render(f5);
    Top.render(f5);
    TopLeft.render(f5);
    TopRight.render(f5);
    BottomLeft.render(f5);
    BottomRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity) {
      this.head.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.head.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 2.0F * par2 * 0.5F;
      this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 2.0F * par2 * 0.5F;
      this.rightarm.rotateAngleZ = 0.0F;
      this.leftarm.rotateAngleZ = 0.0F;
      this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
      this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
      this.rightleg.rotateAngleY = 0.0F;
      this.leftleg.rotateAngleY = 0.0F;

      if (this.isRiding) {
          this.rightarm.rotateAngleX += -((float)Math.PI / 5F);
          this.leftarm.rotateAngleX += -((float)Math.PI / 5F);
          this.rightleg.rotateAngleX = -((float)Math.PI * 2F / 5F);
          this.leftleg.rotateAngleX = -((float)Math.PI * 2F / 5F);
          this.rightleg.rotateAngleY = ((float)Math.PI / 10F);
          this.leftleg.rotateAngleY = -((float)Math.PI / 10F);
      }

      if (this.heldItemLeft != 0) {
          this.leftarm.rotateAngleX = this.leftarm.rotateAngleX * 0.5F - ((float)Math.PI / 10F) * (float)this.heldItemLeft;
      }

      if (this.heldItemRight != 0) {
          this.rightarm.rotateAngleX = this.rightarm.rotateAngleX * 0.5F - ((float)Math.PI / 10F) * (float)this.heldItemRight;
      }

      this.rightarm.rotateAngleY = 0.0F;
      this.leftarm.rotateAngleY = 0.0F;
      float f6;
      float f7;

      if (this.onGround > -9990.0F) {
          f6 = this.onGround;
          this.body.rotateAngleY = MathHelper.sin(MathHelper.sqrt_float(f6) * (float)Math.PI * 2.0F) * 0.2F;
          this.rightarm.rotationPointZ = MathHelper.sin(this.body.rotateAngleY) * 5.0F;
          this.rightarm.rotationPointX = -MathHelper.cos(this.body.rotateAngleY) * 5.0F;
          this.leftarm.rotationPointZ = -MathHelper.sin(this.body.rotateAngleY) * 5.0F;
          this.leftarm.rotationPointX = MathHelper.cos(this.body.rotateAngleY) * 5.0F;
          this.rightarm.rotateAngleY += this.body.rotateAngleY;
          this.leftarm.rotateAngleY += this.body.rotateAngleY;
          this.leftarm.rotateAngleX += this.body.rotateAngleY;
          f6 = 1.0F - this.onGround;
          f6 *= f6;
          f6 *= f6;
          f6 = 1.0F - f6;
          f7 = MathHelper.sin(f6 * (float)Math.PI);
          float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
          this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)f7 * 1.2D + (double)f8));
          this.rightarm.rotateAngleY += this.body.rotateAngleY * 2.0F;
          this.rightarm.rotateAngleZ = MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F;
      }

      if (this.isSneak) {
          this.body.rotateAngleX = 0.5F;
          this.rightarm.rotateAngleX += 0.4F;
          this.leftarm.rotateAngleX += 0.4F;
          this.rightleg.rotationPointZ = 4.0F;
          this.leftleg.rotationPointZ = 4.0F;
          this.rightleg.rotationPointY = 9.0F;
          this.leftleg.rotationPointY = 9.0F;
          this.head.rotationPointY = 1.0F;
      } else {
          this.body.rotateAngleX = 0.0F;
          this.rightleg.rotationPointZ = 0.1F;
          this.leftleg.rotationPointZ = 0.1F;
          this.rightleg.rotationPointY = 12.0F;
          this.leftleg.rotationPointY = 12.0F;
          this.head.rotationPointY = 0.0F;
          //this.headwear.rotationPointY = 0.0F;
      }

      this.rightarm.rotateAngleZ += MathHelper.cos(par3 * 0.09F) * 0.05F + 0.05F;
      this.leftarm.rotateAngleZ -= MathHelper.cos(par3 * 0.09F) * 0.05F + 0.05F;
      this.rightarm.rotateAngleX += MathHelper.sin(par3 * 0.067F) * 0.05F;
      this.leftarm.rotateAngleX -= MathHelper.sin(par3 * 0.067F) * 0.05F;

      if (this.aimedBow)
      {
          f6 = 0.0F;
          f7 = 0.0F;
          this.rightarm.rotateAngleZ = 0.0F;
          this.leftarm.rotateAngleZ = 0.0F;
          this.rightarm.rotateAngleY = -(0.1F - f6 * 0.6F) + this.head.rotateAngleY;
          this.leftarm.rotateAngleY = 0.1F - f6 * 0.6F + this.head.rotateAngleY + 0.4F;
          this.rightarm.rotateAngleX = -((float)Math.PI / 2F) + this.head.rotateAngleX;
          this.leftarm.rotateAngleX = -((float)Math.PI / 2F) + this.head.rotateAngleX;
          this.rightarm.rotateAngleX -= f6 * 1.2F - f7 * 0.4F;
          this.leftarm.rotateAngleX -= f6 * 1.2F - f7 * 0.4F;
          this.rightarm.rotateAngleZ += MathHelper.cos(par3 * 0.09F) * 0.05F + 0.05F;
          this.leftarm.rotateAngleZ -= MathHelper.cos(par3 * 0.09F) * 0.05F + 0.05F;
          this.rightarm.rotateAngleX += MathHelper.sin(par3 * 0.067F) * 0.05F;
          this.leftarm.rotateAngleX -= MathHelper.sin(par3 * 0.067F) * 0.05F;
      }
  }
}
