// Date: 16/08/2014 7:45:46 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package spaceage.client.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelOrganicFemale extends ModelBiped {
	//fields
    public ModelRenderer Base;
    public ModelRenderer Right;
    public ModelRenderer Left;
    public ModelRenderer Top;
    public ModelRenderer TopLeft;
    public ModelRenderer TopRight;
    public ModelRenderer BottomLeft;
    public ModelRenderer BottomRight;

    public ModelOrganicFemale(float par1) {
        super(par1, 0, 64, 64);
        
        textureWidth = 64; //64
        textureHeight = 64; //64
      
      Base = new ModelRenderer(this, 0, 32);
      Base.addBox(-3F, 1F, -3F, 6, 4, 1);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      
      Right = new ModelRenderer(this, 0, 37);
      Right.addBox(3F, 2F, -3F, 1, 3, 1);
      Right.setRotationPoint(0F, 0F, 0F);
      Right.setTextureSize(64, 64);
      Right.mirror = true;
      setRotation(Right, 0F, 0F, 0F);
      
      Left = new ModelRenderer(this, 4, 37);
      Left.addBox(-4F, 2F, -3F, 1, 3, 1);
      Left.setRotationPoint(0F, 0F, 0F);
      Left.setTextureSize(64, 64);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      
      Top = new ModelRenderer(this, 0, 41);
      Top.addBox(-3F, 2F, -4F, 6, 2, 1);
      Top.setRotationPoint(0F, 0F, 0F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      
      TopLeft = new ModelRenderer(this, 0, 44);
      TopLeft.addBox(3F, 3F, -4F, 1, 1, 1);
      TopLeft.setRotationPoint(0F, 0F, 0F);
      TopLeft.setTextureSize(64, 64);
      TopLeft.mirror = true;
      setRotation(TopLeft, 0F, 0F, 0F);
      
      TopRight = new ModelRenderer(this, 4, 44);
      TopRight.addBox(-4F, 3F, -4F, 1, 1, 1);
      TopRight.setRotationPoint(0F, 0F, 0F);
      TopRight.setTextureSize(64, 64);
      TopRight.mirror = true;
      setRotation(TopRight, 0F, 0F, 0F);
      
      BottomLeft = new ModelRenderer(this, 0, 46);
      BottomLeft.addBox(1F, 4F, -4F, 2, 1, 1);
      BottomLeft.setRotationPoint(0F, 0F, 0F);
      BottomLeft.setTextureSize(64, 64);
      BottomLeft.mirror = true;
      setRotation(BottomLeft, 0F, 0F, 0F);
      
      BottomRight = new ModelRenderer(this, 6, 46);
      BottomRight.addBox(-3F, 4F, -4F, 2, 1, 1);
      BottomRight.setRotationPoint(0F, 0F, 0F);
      BottomRight.setTextureSize(64, 64);
      BottomRight.mirror = true;
      setRotation(BottomRight, 0F, 0F, 0F);
      
      this.bipedBody.addChild(Base);
      this.bipedBody.addChild(Left);
      this.bipedBody.addChild(Right);
      
      this.Base.addChild(Top);
      this.Base.addChild(BottomLeft);
      this.Base.addChild(BottomRight);
      
      this.Left.addChild(TopLeft);
      
      this.Right.addChild(TopRight);
    }
  
    public ModelOrganicFemale(float par1, float par2, int par3, int par4) {

  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
