// Date: 16/05/2014 5:06:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package spaceage.client.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStarboost extends ModelBiped {
  //fields
    ModelRenderer midjetpack;
    ModelRenderer jetpackleft;
    ModelRenderer jetpackright;
    ModelRenderer axleright;
    ModelRenderer axleleft;
  
  public ModelStarboost(float f) {
	  super(f, 0, 64, 64);
    textureWidth = 64;
    textureHeight = 64;
    
      midjetpack = new ModelRenderer(this, 0, 32);
      midjetpack.addBox(-2F, -1F, 3F, 4, 4, 1);
      midjetpack.setRotationPoint(0F, 0F, 0F);
      midjetpack.setTextureSize(64, 64);
      midjetpack.mirror = true;
      setRotation(midjetpack, 0F, 0F, 0F);
      jetpackleft = new ModelRenderer(this, 0, 37);
      jetpackleft.addBox(2F, -1F, 3F, 2, 8, 2);
      jetpackleft.setRotationPoint(0F, 0F, 0F);
      jetpackleft.setTextureSize(64, 64);
      jetpackleft.mirror = true;
      setRotation(jetpackleft, 0F, 0F, 0F);
      jetpackright = new ModelRenderer(this, 0, 47);
      jetpackright.addBox(-4F, -1F, 3F, 2, 8, 2);
      jetpackright.setRotationPoint(0F, 0F, 0F);
      jetpackright.setTextureSize(64, 64);
      jetpackright.mirror = true;
      setRotation(jetpackright, 0F, 0F, 0F);
      axleright = new ModelRenderer(this, 0, 57);
      axleright.addBox(6F, 8F, 1F, 1, 1, 1);
      axleright.setRotationPoint(0F, 0F, 0F);
      axleright.setTextureSize(64, 64);
      axleright.mirror = true;
      setRotation(axleright, 0F, 0F, 0F);
      axleleft = new ModelRenderer(this, 0, 59);
      axleleft.addBox(-7F, 8F, 1F, 1, 1, 1);
      axleleft.setRotationPoint(0F, 0F, 0F);
      axleleft.setTextureSize(64, 64);
      axleleft.mirror = true;
      setRotation(axleleft, 0F, 0F, 0F);
      
      this.bipedBody.addChild(midjetpack);
      this.bipedBody.addChild(jetpackleft);
      this.bipedBody.addChild(jetpackright);
      this.bipedRightLeg.addChild(axleright);
      this.bipedLeftLeg.addChild(axleleft);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
  super.render(entity, f, f1, f2, f3, f4, f5);
  setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
