// Date: 16/11/2014 7:38:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package spaceage.common.tile.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHeatGenerator extends ModelBase {
  //fields
    ModelRenderer Base;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Right;
    ModelRenderer Left;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape72;
    ModelRenderer Shape82;
    ModelRenderer Shape92;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
  
  public ModelHeatGenerator() {
    textureWidth = 64;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-3F, 8F, -4F, 11, 16, 12);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 28);
      Shape1.addBox(-3F, -2F, -4F, 5, 4, 8);
      Shape1.setRotationPoint(-5F, 12F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.5235988F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 26, 28);
      Shape2.addBox(-3F, -2F, -4F, 5, 4, 8);
      Shape2.setRotationPoint(-5F, 12F, 0F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.5235988F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 40);
      Shape3.addBox(-3F, -2F, -4F, 5, 4, 8);
      Shape3.setRotationPoint(-5F, 12F, 0F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, -1.570796F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 46, 0);
      Shape4.addBox(-3F, -2F, -1F, 5, 4, 2);
      Shape4.setRotationPoint(-5F, 22F, 0F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 46, 6);
      Shape5.addBox(-3F, -2F, -1F, 5, 4, 2);
      Shape5.setRotationPoint(-5F, 22F, 0F);
      Shape5.setTextureSize(64, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 1.047198F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 46, 12);
      Shape6.addBox(-3F, -2F, -1F, 5, 4, 2);
      Shape6.setRotationPoint(-5F, 22F, 0F);
      Shape6.setTextureSize(64, 64);
      Shape6.mirror = true;
      setRotation(Shape6, -1.047198F, 0F, 0F);
      Right = new ModelRenderer(this, 0, 52);
      Right.addBox(-2F, -5F, -3F, 3, 11, 1);
      Right.setRotationPoint(-5F, 16F, 0F);
      Right.setTextureSize(64, 64);
      Right.mirror = true;
      setRotation(Right, 0.2094395F, 0F, 0F);
      Left = new ModelRenderer(this, 8, 52);
      Left.addBox(-2F, -5F, 2F, 3, 11, 1);
      Left.setRotationPoint(-5F, 16F, 0F);
      Left.setTextureSize(64, 64);
      Left.mirror = true;
      setRotation(Left, -0.2094395F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 16, 52);
      Shape7.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape7.setRotationPoint(0F, 7F, -6F);
      Shape7.setTextureSize(64, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 16, 52);
      Shape8.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape8.setRotationPoint(0F, 7F, -6F);
      Shape8.setTextureSize(64, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 1.047198F, 0F);
      Shape9 = new ModelRenderer(this, 16, 52);
      Shape9.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape9.setRotationPoint(0F, 7F, -6F);
      Shape9.setTextureSize(64, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, -1.047198F, 0F);
      Shape72 = new ModelRenderer(this, 16, 52);
      Shape72.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape72.setRotationPoint(5F, 7F, -6F);
      Shape72.setTextureSize(64, 64);
      Shape72.mirror = true;
      setRotation(Shape72, 0F, 0F, 0F);
      Shape82 = new ModelRenderer(this, 16, 52);
      Shape82.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape82.setRotationPoint(5F, 7F, -6F);
      Shape82.setTextureSize(64, 64);
      Shape82.mirror = true;
      setRotation(Shape82, 0F, 1.047198F, 0F);
      Shape92 = new ModelRenderer(this, 16, 52);
      Shape92.addBox(-1F, 9F, -2F, 2, 8, 4);
      Shape92.setRotationPoint(5F, 7F, -6F);
      Shape92.setTextureSize(64, 64);
      Shape92.mirror = true;
      setRotation(Shape92, 0F, -1.047198F, 0F);
      Shape10 = new ModelRenderer(this, 53, 59);
      Shape10.addBox(-1F, 13F, -7F, 2, 3, 2);
      Shape10.setRotationPoint(0F, 0F, 0F);
      Shape10.setTextureSize(64, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 53, 59);
      Shape11.addBox(4F, 13F, -7F, 2, 3, 2);
      Shape11.setRotationPoint(0F, 0F, 0F);
      Shape11.setTextureSize(64, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 53, 56);
      Shape12.addBox(-1F, 13F, -5F, 2, 2, 1);
      Shape12.setRotationPoint(0F, 0F, 0F);
      Shape12.setTextureSize(64, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 53, 56);
      Shape13.addBox(4F, 13F, -5F, 2, 2, 1);
      Shape13.setRotationPoint(0F, 0F, 0F);
      Shape13.setTextureSize(64, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Right.render(f5);
    Left.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape72.render(f5);
    Shape82.render(f5);
    Shape92.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
